// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCJLs6Dj-YfuZqiAbSRo66ZPLvabhBtayk',
    appId: '1:805091883304:web:471a80c52445d4411f781d',
    messagingSenderId: '805091883304',
    projectId: 'dobites-apps-ca1e5',
    authDomain: 'dobites-apps-ca1e5.firebaseapp.com',
    storageBucket: 'dobites-apps-ca1e5.firebasestorage.app',
    measurementId: 'G-1VE2HQVRMM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDfII1hAZxe_oLSOl_WUzXiIlOM6BVBGsI',
    appId: '1:805091883304:android:e2e59f095c4314e31f781d',
    messagingSenderId: '805091883304',
    projectId: 'dobites-apps-ca1e5',
    storageBucket: 'dobites-apps-ca1e5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAbV2PRBWEzuUX-djfh3runRB_0SuZPtWM',
    appId: '1:805091883304:ios:d4625ce44d58af581f781d',
    messagingSenderId: '805091883304',
    projectId: 'dobites-apps-ca1e5',
    storageBucket: 'dobites-apps-ca1e5.firebasestorage.app',
    iosBundleId: 'com.example.dobites',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAbV2PRBWEzuUX-djfh3runRB_0SuZPtWM',
    appId: '1:805091883304:ios:d4625ce44d58af581f781d',
    messagingSenderId: '805091883304',
    projectId: 'dobites-apps-ca1e5',
    storageBucket: 'dobites-apps-ca1e5.firebasestorage.app',
    iosBundleId: 'com.example.dobites',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCJLs6Dj-YfuZqiAbSRo66ZPLvabhBtayk',
    appId: '1:805091883304:web:67d5cac0b56f9cc71f781d',
    messagingSenderId: '805091883304',
    projectId: 'dobites-apps-ca1e5',
    authDomain: 'dobites-apps-ca1e5.firebaseapp.com',
    storageBucket: 'dobites-apps-ca1e5.firebasestorage.app',
    measurementId: 'G-6BMV9GY3F2',
  );
}
